version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file: .env
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-boot-marvel-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-marvel
    volumes:
      - .:/app       # Monta el proyecto local en el contenedor
      - ~/.m2:/root/.m2  # Reutiliza el caché de Maven en tu máquina local
    env_file: .env
    ports:
      - "8080:8080"  # Expone el puerto 8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev # Configura el perfil de Spring para desarrollo
    command: ./mvnw spring-boot:run # Inicia el proyecto en modo desarrollo
    depends_on:
      - mysql
    networks:
      - spring-boot-marvel-network

volumes:
  mysql-data:

networks:
  spring-boot-marvel-network: